web_wiki/campaigns/urls.py
from django.urls import path
from . import views

app_name = 'campaigns' #specify that these urls are in the app 'campaigns'

urlpatterns = [
    path('', views.campaigns_list, 
         name='list'), #name for the link
    path('new-campaign/', views.campaign_new, 
         name='new-campaign'), #name for the link
    path('<slug:slug>', views.campaign_page, #any hard defined url should go before this otherwise it wil be considered as a slug
         name='page'), 
]

web_wiki/playground/urls.py
from django.urls import path
from . import views

# URLConf
urlpatterns = [
    path('hello/', views.say_hello)
]

web_wiki/users/urls.py
from django.urls import path
from . import views

app_name = 'users' #specify that these urls are in the app 'campaigns'

urlpatterns = [
    path('register/', views.register, name='register'), 
    path('login/', views.login_view, name='login'), 
    path('logout/', views.logout_view, name='logout'), 
]

web_wiki/wiki/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
import debug_toolbar
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('campaigns/', include('campaigns.urls')),
    path('users/', include('users.urls')),
    path('playground/', include('playground.urls')), #any request starting with playground will be handled by the respective playground module
    path('__debug__/', include(debug_toolbar.urls)),
]

#specify where to find images
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_wiki/campaigns/models.py
from django.db import models
from django.utils.text import slugify

class Campaign(models.Model):
    title = models.CharField(max_length=200, unique=True)  # Campaign name
    description = models.TextField(blank=True)  # Optional campaign details
    start_date = models.DateField()  # Campaign start date
    end_date = models.DateField(null=True, blank=True)  # Optional end date
    slug = models.SlugField(blank=True, unique=True)
    icon = models.ImageField(default='placeholder.png', blank=True)

    def __str__(self):
        return self.title  # Display campaign name in admin panel
    
    def save(self, *args, **kwargs):
        if not self.slug:  # Only generate slug if it's not set
            self.slug = slugify(self.title)
        super().save(*args, **kwargs) 


web_wiki/characters/models.py
from django.db import models

class Character(models.Model):
    """Base model for both Player and Non-Player Characters"""
    name = models.CharField(max_length=100)
    race = models.CharField(max_length=50)
    alignment = models.CharField(max_length=50)
    backstory = models.TextField(blank=True)
    campaign = models.ForeignKey('campaigns.Campaign', on_delete=models.CASCADE, related_name="characters")

    def __str__(self):
        return self.name

class PlayerCharacter(Character):
    """Model for Player Characters (PCs), with an associated character sheet PDF"""
    character_class = models.CharField(max_length=50)
    player_name = models.CharField(max_length=100)
    #portrait = models.ImageField(default='placeholder_image.png', blank=True)
    character_sheet = models.FileField(upload_to='character_sheets/', blank=True, null=True)  # PDF upload

class NonPlayerCharacter(Character):
    """Model for Non-Player Characters (NPCs), no extra fields needed"""
    role = models.CharField(
        max_length=50, 
        choices=[('ALLY', 'Ally'), ('ENEMY', 'Enemy'), ('NEUTRAL', 'Neutral'), ('OTHER', 'Other')],
        default='NEUTRAL'
    )


web_wiki/items/models.py
from django.db import models

class Item(models.Model):
    name = models.CharField(max_length=50)
    rarity = models.CharField(
        max_length=50, 
        choices=[('COMMON', 'Common'), ('UNCOMMON', 'Uncommon'), 
                 ('RARE', 'Rare'), ('EPIC', 'Epic'),
                 ('LEGENDARY', 'Legendary'), ('ARTIFACT', 'Artifact'),
                 ('VARIES', 'Varies')],
        blank=True
    )
    is_magic = models.BooleanField()
    requires_attunement  = models.BooleanField()
    description = models.TextField(blank=True)
    
    def __str__(self):
        return self.name


web_wiki/locations/models.py
from django.db import models

class Location(models.Model):
    name = models.CharField(max_length=50)
    major_geographical_area = models.CharField(max_length=50)
    description = models.TextField(blank=True)

web_wiki/users/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(blank=True)
    join_date = models.DateField()

    def __str__(self):
        return self.name

web_wiki/campaigns/views.py
from django.shortcuts import render
from .models import Campaign
from django.contrib.auth.decorators import login_required


def campaigns_list(request):
    campaigns = Campaign.objects.all().order_by('start_date')
    return render(request, 'campaigns_home.html',  #no need to specify template because set in settings
                  { 'campaigns': campaigns}) # return data relative to the Campaign objects


def campaign_page(request, slug):
    campaign = Campaign.objects.get(slug=slug)
    return render(request, 'campaign_page.html',  #render specific page
                  { 'campaign': campaign}) # return data relative to the Campaign objects

@login_required(login_url='/users/login/')
def campaign_new(request):
    
    return render(request, 'new_campaign.html')

web_wiki/characters/views.py
from django.shortcuts import render

# Create your views here.

web_wiki/items/views.py
from django.shortcuts import render

# Create your views here.

web_wiki/locations/views.py
from django.shortcuts import render

# Create your views here.

web_wiki/playground/views.py
from django.shortcuts import render
from django.http import HttpResponse

def calculate():
    x = 1
    y = 2
    return x

def say_hello(request): 
    x = calculate()
    return render(request, 'hello.html', {'name': 'Mylo'})

web_wiki/users/views.py
from django.shortcuts import render, redirect
#from .models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

"""
def users_list(request):
    users = User.objects.all().order_by('name')
    return render(request, 'users_list.html', {'users': users})
"""

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save()) #form.save will also return a user value
            return redirect("campaigns:list") #redirect to app 'campaigns', urls with name 'list'
    else: #ie if not submitted via POST method
        form = UserCreationForm() #create empty form
    return render(request, 'register.html', #and return empty form
                  {'form': form})
    
    
def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user()) #fetch user from form if valid
            if "next" in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('campaigns:list')
    else:
        form = AuthenticationForm()
        
    return render(request, 'login.html', #and return empty form
                  {'form': form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('campaigns:list')

web_wiki/wiki/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

web_wiki/campaigns/templates/campaign_page.html
{% extends 'layout.html' %}

{% block title %}
    {{ campaign.title }}
{% endblock %}

{% block content %}
    <section>
        <img 
        class="banner"
        src="{{ campaign.icon.url }}"
        alt="{{ campaign.title }}"
        />
        <h1>{{ campaign.title }}</h1>
        <p>{{ campaign.start_date }}</p>
        <p>{{ campaign.description }}</p>
    </section>
{% endblock %}

web_wiki/campaigns/templates/campaigns_home.html
{% extends 'layout.html' %}

{% block title %}
    Campaigns
{% endblock %}

{% block content %}
    <section>
        <h1>Campaigns List</h1>

        {% for campaign in campaigns%}
            <article class="campaign">
                <h2>
                    <a href="{% url 'campaigns:page' slug=campaign.slug %}"> <!--uses name given in the url file-->
                        {{ campaign.title }}
                    </a>
                </h2>
                <p>{{ campaign.start_date }}</p>
                <p>{{ campaign.description }}</p>
            </article>
        {% endfor %}
    </section>
{% endblock %}

web_wiki/campaigns/templates/new_campaign.html
{% extends 'layout.html' %}

{% block title %}
    New Campaign
{% endblock %}

{% block content %}
    <section>
        <h1>New Campaign</h1>
    </section>
{% endblock %}

web_wiki/playground/templates/hello.html
<html>
    <body>
        {% if name %}
        <h1>Hello {{ name }}</h1>
        {% else %}
        <h1>Hello World</h1>
        {% endif %}
    </body>
</html>


web_wiki/templates/about.html
{% extends 'layout.html' %}

{% block title %}
    About
{% endblock %}

{% block content %}
    <h1>About</h1>
    <p>Also check out the <a href="/">home</a> page.</p>
{% endblock %}

web_wiki/templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Home</h1>
    <p>Also check out the <a href="/about">about</a> page.</p>
{% endblock %}

web_wiki/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Example
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <nav>
        <a href="/">
            <span role="img" aria-label="Home" title="Home">🏠</span>
        </a> |
        <a href="/about">
            <span role="img" aria-label="About" title="About">❔</span>
        </a> |
        <a href="{% url 'campaigns:list' %}">
            <span role="img" aria-label="Campaigns" title="Campaigns">🛣️</span>
        </a> | <!-- fetch the url named 'campaigns', see campaigns/urls-->
 
        {% if user.is_authenticated %}
            <a href="{% url 'campaigns:new-campaign' %}">
                <span role="img" aria-label="New Campaign" title="New Campaign">🆕</span>
            </a> |
            <form class="logout" action="{% url 'users:logout' %}" method="POST">
                {% csrf_token %}
                <button class="logout-button" aria-label="Log out", title="Log out">👋</button>
            </form>
        {% else %}
            <a href="{% url 'users:register' %}">
                <span role="img" aria-label="Sign up" title="Sign up">🪧⬆️</span>
            </a> | 
            <a href="{% url 'users:login' %}">
                <span role="img" aria-label="Log in" title="Log in">🪵⬅️</span>
            </a>
        {% endif %}
        
        
    </nav>
    <main>
        {% block content %}

        {% endblock %}
    </main>
</body>
</html>

web_wiki/users/templates/login.html
{% extends 'layout.html' %}

{% block title %}
    User Log-in
{% endblock %}

{% block content %}
    <h1>User Log-in</h1>
    <form class="form-with-validation" action="/users/login/" 
    method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}"/>
        {% endif %}
        <button class="form-Submit">Log-in</button>
    </form>
{% endblock %}

web_wiki/users/templates/register.html
{% extends 'layout.html' %}

{% block title %}
    Register a New User
{% endblock %}

{% block content %}
    <h1>Register a New User</h1>
    <form class="form-with-validation" action="/users/register/" 
    method="post">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit">Submit</button>
    </form>
{% endblock %}

web_wiki/users/templates/users_list.html
{% extends 'layout.html' %}